spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liBtEklRjLP2ZKcL
            clientSecret: edba6eda91eca1533e13ff1ccc9b66f2b9286f2f
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
server:
  port: 8081
